/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package net.mafro.android.wakeonlan;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int history=0x7f060005;
        public static final int history_row_ip=0x7f060002;
        public static final int history_row_mac=0x7f060001;
        public static final int history_row_port=0x7f060003;
        public static final int historyview=0x7f060004;
        public static final int icon=0x7f060000;
        public static final int ip=0x7f060009;
        public static final int mac=0x7f060008;
        public static final int menu_delete=0x7f06000d;
        public static final int menu_wake=0x7f06000c;
        public static final int port=0x7f06000a;
        public static final int send_wake=0x7f06000b;
        public static final int title=0x7f060007;
        public static final int wakeview=0x7f060006;
    }
    public static final class layout {
        public static final int history_row=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class menu {
        public static final int history_menu=0x7f050000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int button_wake_en=0x7f040001;
        public static final int ip_en=0x7f040006;
        public static final int mac_en=0x7f040005;
        public static final int menu_delete_en=0x7f04000a;
        public static final int menu_wake_en=0x7f040009;
        public static final int port_en=0x7f040007;
        public static final int tab_history_en=0x7f040002;
        public static final int tab_wake_en=0x7f040003;
        public static final int test_mac=0x7f040008;
        public static final int title_en=0x7f040004;
    }
}
